apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: crud-app
type: Opaque
data:
  # root password: rootpassword (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # database name: crud_app (base64 encoded)
  mysql-database: Y3J1ZF9hcHA=
